Makefile

add top level Makefile

---

.github/workflows/container-image.yml

github actions: use top level target for image build

---

.github/workflows/container-image.yml
Makefile
hack/test-samba-container.sh
images/client/Makefile
images/samba/Makefile

This adds a simple test for the container.
The test runs the container, and executes smbclient to simply list the shares.

Add a simple test

---

.github/workflows/container-image.yml

Push to quay after push to master

---

Makefile

Prefer podman over docker if both are available

---

README.md
examples/kubernetes/sambadeployment.converged.yml
examples/kubernetes/sambadeployment.yml
examples/kubernetes/sambapod.yml

Update README.md and kubernetes example files to reflect a number of recent changes to the container and related materials.

doc and example file cleanups

---

images/server/Dockerfile.fedora

server: require newer version of sambacc

---

.github/workflows/container-image.yml
Makefile
images/ad-server/Containerfile
images/ad-server/populate.sh
images/ad-server/provision.sh
images/ad-server/run.sh

Files taken from https://hg.sr.ht/~phlogistonjohn/samba-ad-container
For a start, domain, users, etc, are all hard-coded.
We will generalize as we move on.
Co-authored-by: John Mulligan <jmulligan@redhat.com>

Add basic ad-server container

---

examples/kubernetes/samba-ad-server-deployment.yml

samba-ad-server: add example kubernetes deployment

---

images/server/Dockerfile.fedora

server: require newer sambacc version

---

.github/workflows/container-image.yml
hack/test-samba-ad-server-kubernetes.sh

This PR adds kubernetes tests using k3d.
Based on PR #32 .

Add kubernetes tests for the ad-server deployment

---

images/ad-server/provision.sh

Fixes: #39
Signed-off-by: Michael Adam <obnox@redhat.com>

ad-server: change default domain to testdom.sink.test

---

images/ad-server/Containerfile
images/server/Dockerfile.fedora
images/server/Dockerfile.nightly

This sambacc version has improvements around logging and better dns-reg behavior wrt
ctdb enabled instances.

bump sambacc "version"

---

.github/workflows/container-image.yml
Makefile
images/ad-server/Containerfile
images/ad-server/install-packages.sh
images/server/install-packages.sh
tests/files/samba-ad-server-deployment.yml
tests/files/samba-domain-member-pod.yml
tests/test-deploy-ad-member.sh
tests/test-deploy-ad-server.sh

This is something I had running under my fork for sometime and now rebased on top of https://github.com/samba-in-kubernetes/samba-container/pull/66.
@phlogistonjohn let me know your thoughts..

Build/Test/Push AD container images based on nightly Samba RPMs

---

Makefile
images/ad-server/Containerfile
images/server/Containerfile

server: use fedora 35 source image

---

.github/workflows/container-image.yml
Makefile
images/toolbox/Containerfile

Create dedicate image for developer's or power-user admin and testing operations. Similar to rook's toolbox.

samba toolbox

---

.gitignore

gitignore: add temporary files from Makefile targets

---

.github/mergify.yml

config taken from the sambacc config and adjusted

github: Add mergify configuration

---

.github/mergify.yml

I wish there was an easier way to do this but I couldn't find anything useful in the mergify docs.

github: update mergify config to match new matrix

---

.github/workflows/container-image.yml

- [container-image-artifact-upload](https://github.com/marketplace/actions/container-image-artifact-upload)
- [container-image-artifact-download](https://github.com/marketplace/actions/container-image-artifact-download)

workflows: Use new GitHub action with podman support

---

.github/workflows/container-image.yml
Makefile

These tags are designed to not overlap on major build parameters. This is a stepping stone PR, my next goal is to move the package source into the matrix (default or nightly). But I like a small delta for reviews and this tests out the CI changes with this small step first.

github: switch to using fqin style tags in the ci yaml
