- images/client/Makefile
- images/samba/Makefile
It is better to have one .PHONY statement for each target,
next to the target. Less error-prone.
> makefiles: distribute .PHONY

- Makefile
- images/samba/Dockerfile.fedora
The sambacc projects provides a script 'samba-container' meant to help
manage samba within a container environment. Fedora provides us
with some newer packages, etc.
> [RFC] samba: add a new dockerfile based on fedora and sambacc

- Makefile
Moving away from the personal repo.
Created a new org "samba.org" and repos with more
systematic names under that org.
Use them by default.
> Use new org/repos under quay.io/samba.org by default

- Makefile
Unlike podman, docker can not push from a local name to a remote name,
and only takes one argument: the remote name. Since I only have podman
locally I mistakenly changed the makefiles to require the podman
approach. This fixes that by applying both local and remote names at
build time and then pushing with only one argument.
> makefile: fix pushing with docker cli

- .github/workflows/container-image.yml
The env has both docker and podman commands, and the
Makefile has some detection logic that currently prefers
docker.
We are using "podman login" in the yaml, so enforcing
the use of podman in the workflow to fix the post-merge
push action.
> github actions: enforce use of podman in the push action

- examples/podman/README.md
- examples/podman/config.json
- examples/podman/smb-wb-pod.sh
Adds a script, config json template, and readme file to give a brief
into to running samba containers as a domain member.
> examples: add podman based AD joined winbind+smbd pod

- examples/kubernetes/sambadmpod.yml
- images/server/Dockerfile.fedora
This adds a basic, but functional, example of running a pod in kubernetes with both sbmd and winbind for use as a domain member smb server.
The YAML contains a ConfigMap, secret, and pod configuration. One must edit parts of the yaml (and the embedded JSON) to match the  user's domain.
This currently needs a new build of the samba server container to work thus it won't work without the commit bumping the version of sambacc in use. If you want I can split these into separate PRs. I wasn't sure if that was needed as this is "just" an example.
> examples: add a yaml for smbd+winbind pod

- images/server/Dockerfile.fedora
Now that the sambacc projects is pushing its images to
the sambacc repo under quay.io/samba.org, let's use this
image repo instead of John's personal one. :-)
> images: use the sambacc container from quay.io/samba.org

- examples/kubernetes/sambadmpod.yml
- images/server/Dockerfile.fedora
The init containers are responsible for early env setup as well
as handling (if possible) and requiring domain joins.
This depends on PR #25 as the init containers require newer versions of sambacc.
> kubernetes: update samba dm pod yaml to use init containers

- .github/workflows/container-image.yml
At the moment the images in samba-server appear to have manifest format
"v2s1" which is rather suboptimal. We would prefer oci or at least
docker "v2s2" (version 2 schema 2).
This change is an experiment to see if tweaking this variable gives
us a better result when the CI job pushes to quay.io.
-- Note: this won't do anything particularly useful until it's merged. So once we're certain it doesn't break the build only merging it will do anything helpful.
> workflows: see if setting BUILDAH_FORMAT creates oci images on quay.io

- images/ad-server/populate.sh
It was erroneously using "range" instead of "seq"
in enumeration...
> ad-server: fix populate script

- images/server/Dockerfile.fedora
To make it simpler to develop and test changes to sambacc in the server image, allow the use of build args specifying the version/tag/hash and repo from which to build the sambacc wheel.
Split the package install RUN from installing sambacc RUN; by splitting the build this way the layer containing the system packages and that containing sambacc install can be independently cached. The (probably) less frequently changing packages layer may be reused more often than the more frequently changing (for now) sambacc layer.
> server image: make the the server image build more flexible

- examples/kubernetes/samba-ctdb-dm-sset.yml
- examples/kubernetes/samba-ctdb-sset.yml
- images/server/Dockerfile.fedora
These changes add the ctdb package to the container, which is pretty harmless on its own, as well as the most recent sambacc which can "manage" aspects of ctdb if you opt in to the experimental ctdb support.
I've included an example yaml that makes use of a StatefulSet to demonstrate how the most basic integration of ctdb into a samba pod under k8s might work.
I'm putting this out here in a half-baked state so that others have an opportunity to try it out and provide feedback.
> experimental ctdb support

- Makefile
Typically caused by podman remote problems as noted.
Fixes #53
> makefile: handle the case where podman exists but is not working

- examples/kubernetes/samba-ctdb-dm-sset.yml
Use the vfs_fileid plugin with fsid when using a clustered fs on a PV on
multiple nodes.
Fixes: issue #49
Signed-off-by: Sachin Prabhu <sprabhu@redhat.com>
> kubernetes examples: Use vfs_fileid in generated smb.conf

- images/server/Dockerfile.fedora
- images/server/Dockerfile.nightly
sambacc now outputs wheels versioned based on the vcs tags and
vcs hash etc. as needed. It also now puts builds in a specific
"dist dir" under /srv when requested. This change makes the
samba-container match the new sambacc behavior.
> server: match recent changes to sambacc packaging approach

- .github/workflows/container-image.yml
When someone forks the repository, they automatically get the GitHub actions workflow which would then run the push job without proper credentials to push images to quay.io/samba.org registry. Therefore we limit it by checking whether we are within original repository or not.
> Run push jobs only within repository and not on forks

- .github/workflows/container-image.yml
- Makefile
- images/server/install-sambacc.sh
- tests/common.sh
- tests/test-deploy-ad-member.sh
- tests/test-deploy-ad-server.sh
- tests/test-remove-ad-member.sh
- tests/test-remove-ad-server.sh
- tests/test-samba-ad-server-kubernetes.sh
Based on PR: #59 
The samba-container project holds a fair number of shell scripts. Let's use the `shellcheck` static checker on them to avoid common errors.
The patches contain small fix-ups for the scripts, a new makefile rule, and a CI rule to execute the make rule.
> Add shellcheck check rule

- Makefile
s / NIG**HLT**Y_AD_SERVER_REPO_NAME / NIG**HTL**Y_AD_SERVER_REPO_NAME
> build: Fix a typo for push-nightly-ad-server target

- images/ad-server/install-packages.sh
- images/server/install-packages.sh
The new permissions feature to sambacc required the python xattr module.
Signed-off-by: Sachin Prabhu <sprabhu@redhat.com>
> Install python3-pyxattr package on server image

- images/ad-server/Containerfile
- images/ad-server/install-sambacc.sh
- images/server/Containerfile
- images/server/install-sambacc.sh
Depends on: samba-in-kubernetes/sambacc#40
Now that sambacc's build image can generate an RPM, use that to install sambacc. I retained the ability to install from a python wheel for now in case we find something strange with the RPM and need to revert. In the not too distant future, if all is fine with the rpm, we can probably drop support from installing from the wheel (unless we decide we want to support non-rpm distros?)
> Install sambacc from rpm

- images/ad-server/Containerfile
- images/ad-server/install-packages.sh
- images/server/Containerfile
- images/server/install-packages.sh
This applies to the server and ad-server container images.
The planned release branch will be able to set the SAMBA_VERSION_SUFFIX build arg to a specific version.
> Specify a version suffix to pin samba versions

- .github/workflows/container-image.yml
This is an attempt to evaluate and measure the effort to reuse images built in earlier steps while running actual tests so as to improve overall test time. Here we make use of [upload-artifact](https://github.com/actions/upload-artifact) in build step and [download-artifact](https://github.com/actions/download-artifact) in actual test run step.
fixes: #73
> workflows: Share images between jobs

- images/ad-server/Containerfile
- images/server/Containerfile
Expects Fedora36 to be maintained until mid 2023.
Signed-off-by: Shachar Sharon <ssharon@redhat.com>
> images: bump base image to fedora36

- images/server/Containerfile
Use the detection mechanism from sambacc(https://github.com/samba-in-kubernetes/sambacc/pull/50) via `SAMBA_SPECIFICS` env variable to indicate the presence of new/replaced administrative sub-command 'leader' for CTDB.
> images/server: Use new CTDB 'leader' admin sub-command

- images/client/Containerfile
Align client to same base image as server and ad-server, as well as base image used by sambacc. Allows the container engine to share image-layers between containers.
Signed-off-by: Shachar Sharon <ssharon@redhat.com>
> client: use fedora36 as base image

- Makefile
The build rule exists to build everything, so it should include the new toolbox container too.
> makefile: add build-toolbox to general build rule

- README.md
This restructures and expands our existing readme. This is in preparation for further documentation of the various things you can do with the images as well as documenting the sambacc JSON config file format (in the sambacc repo).
> readme: refresh the entire readme

- docs/server.md
This is the first, somewhat extensive, document explaining most of the features we provide for samba server container image.
> docs: add docs for samba-server containers

- .github/workflows/container-image.yml
- images/toolbox/Containerfile
When using samba-client as base image for toolbox, we get an enigmatic failure due to dnf dependencies conflict. This does not appear to be related to samba packages but rather to something in dnf internal database. Avoid this problem by using fedora:36 as base image.
Refs:
https://github.com/samba-in-kubernetes/samba-container/issues/96
Signed-off-by: Shachar Sharon <ssharon@redhat.com>
> toolbox: use fedora36 as base image

- .github/workflows/container-image.yml
- images/client/Containerfile
- images/toolbox/Containerfile
This change partially reverts 91b87790ca267fca50b2b90acd90bf32f5830dc6 and explicilty installs **systemd** along with **samba-client** so that package conflict problem from https://github.com/samba-in-kubernetes/samba-container/issues/96 never arises.
Additionally share _samba-client_ image to be consumed within _samba-toolbox_ build process for GitHub action workflow. 
fixes #96
> images: Use `samba-client` as base image for `samba-toolbox` build

- .github/mergify.yml
The check is named "build-nightly-ad-server" not
"build-nightly-adserver".
Until this issue is resolved most (all?) PRs won't automerge using mergify.
> github: fix minor "spelling" mistake in mergify rules

- .gitignore
- Makefile
- Makefile.opensuse
- images/ad-server/Containerfile.fedora
- images/ad-server/Containerfile.opensuse
- images/client/Containerfile.fedora
- images/client/Containerfile.opensuse
- images/server/Containerfile.fedora
- images/server/Containerfile.opensuse
- images/toolbox/Containerfile
- images/toolbox/Containerfile.fedora
- images/toolbox/Containerfile.opensuse
This is a new proposal for adding openSUSE images, using new Containerfiles. This moves all the existing Containerfile names to Containerfile.fedora, and creates new Containerfile names called Containerfile.opensuse. I've also added a couple of opencontainer flags to the Fedora containers (excluding the build time/versions/etc since I don't know how this works in Fedora).
I intentionally excluded the opensuse images from the general build, since we won't be using the Makefile for generating our images anyway, though I added the make rule 'build-opensuse' for easy test builds. Also, I included 'build-opensuse-server' in `make test` (and have it run a the tests on it).
FYI, these builds currently fail locally, because the sambacc package hasn't been approved for Tumbleweed yet (I'm working …
> Proposal2: openSUSE base images

- Makefile
Update the Makefile to improve the regularity and DRY-ness of the
container build rules. Each build rule is now made up of common
top-level variables, of which mostly just the names and default build
args change.
I think this improves the readability of the file as well as making it
easier to include the Makefile and then re-use the _img_build target
rather than copy and paste the  build + buildfile creation commands.
---
Add some "section" level header comments to help future
additions/changes to this file be organized. It also reorders a few
of the rules in order to follow a consistent pattern - in particular
every container build rule will be followed by the matching container
push rule.
> Makefile organization and cleanups

- Makefile
This change improves the definitions of buildfile variables by introducing a variable for the filename prefix, '.build'.
As a side effect, the clean target which previously just deleted a somewhat arbitrary explicit list of buildfiles and was therefore error-prone, could be
made more systematic and robust by introducing the use of a wildcard. This way, the clean target should continue working even if future changes change the exact names of buildfiles.
This change was separated out of PR #107  where it was a mere byproduct
> Makefile: improve buildfile handling, including cleanup

- .github/mergify.yml
In samba-operator we updated the mergify rules to label PRs that are "old", applying a "priority-review" label to the PR.  See the samba-operator commit d2e55778920d3ab0bfd9c7f820fe5b1f2b9de4e4 for full details.
> github: sync mergify rules that handle aged PRs

- images/ad-server/install-packages.sh
- images/server/install-packages.sh
Temporarily remove jsonschema from our packages list. sambacc tries to
use this package but is not compatible with the version in fedora 36
> drop jsonschema rpms

- images/ad-server/install-packages.sh
- images/toolbox/Containerfile.fedora
- images/toolbox/Containerfile.opensuse
Including tdb tools will permit the use of programs like tdbbackup
to be used from within the AD DC container.
Fixes: #113
----
Also add tdb-tools to the toolbox images, since they are tools.
> add tdb-tools to ad-server and toolbox images

- images/ad-server/Containerfile.opensuse
Including tdb tools will permit the use of programs like tdbbackup to be used from within the AD DC container.
This was added to the Fedora container, so let's add it to the openSUSE container for consistency.
> ad-server: add tdb-tools to installed packages

- .github/workflows/container-image.yml
- .gitlint
- Makefile
- hack/install-tools.sh
Fixes: #121
I'm perfectly happy with the first commit in this series. 
Everything including and after adding the 'install-tools.sh' I'm a bit iffy on. I tried multiple approaches and nothing pleased me. This current version is based on the workflow we have in samba-container where if the makefile determines a prerequisite tool is not present it tries to locally install one in the `.bin` subdir under the repo root.  Unlike the samba-operator version I tried really hard to avoid adding a lot of boilerplate to the makefie now and in the future and used some pattern matching to avoid it. Still, I'm not exactly thrilled with the implementation, but it was working OK for me.
> Add gitlint support to samba-container

- .gitignore
- Makefile
- images/ad-server/Containerfile.fedora
- images/ad-server/install-sambacc.sh
- images/common/install-sambacc-common.sh
- images/server/Containerfile.centos
- images/server/Containerfile.fedora
- images/server/install-sambacc.sh
The script to install sambacc was a near copy-n-paste from server to ad-server. Any future changes to one script has to be copied back to the other. This change tries to simplify the install of sambacc by creating a common script and then sourcing it from each specific install script.
Other simplifications too.
> install sambacc using common script

- images/ad-server/Containerfile.fedora
- images/common/install-sambacc-common.sh
- images/server/Containerfile.centos
- images/server/Containerfile.fedora
Depends on: #118
Update the sambacc install script to default to using our new COPR by default if there's no "distdir" provided. Switch the server fedora, server centos, and ad-server fedora container files to use the COPR by no longer building the RPM in a builder image.
> install sambacc from COPR

- images/server/install-packages.sh
Install the cephfs and iouring vfs packages. These vfs modules are part of samba but are not packaged with the base server. Add cephfs so we can experiment with it soon.
Add iouring so we can experiment with it later.
Fixes: #95
> server: install some vfs packages

- images/ad-server/Containerfile.fedora
- images/client/Containerfile.fedora
- images/server/Containerfile.fedora
Depends on: #127 
Fixes: #111 
With the recent release of Fedora 38, fedora 36 is now EOL. We should move to a still-supported version.
Additionally, this should move the container images to a version where all optional features of sambacc work. This should be automatically activated by the sambacc RPM packages `Recommends` lines on fc37 and later.
> Update fedora image bases to version 37

- Makefile
Aside from a couple of cleanup commits this series contains two significant changes:
1. It adds a new form of image name/tag I've nicknamed the "fully qualified image name" that is a long tag containing a bunch of details about the image - mainly package source (default or nightly), base os, and architecture. Plus developers can add a final optional extra value when hacking on things.
2. Add a BUILD_ARCH variable that you can pass to make to have it build an architecture other than the native one.
use it like `make BUILD_ARCH=arm64` (assuming an amd64 machine).
Note that this uses a standard way to request arm64 (or other) architectures using     the `--arch` flag to podman (untested on docker (yet)). This makefile change does *nothing* to     attempt to make that flag work on a …
> Add preliminary support for building arm64 images

- .github/workflows/container-image.yml
- .gitignore
- .yamllint.yaml
- Makefile
- hack/install-tools.sh
This PR adds yaml lint checking to the tests and to the github  CI workflows.
The code is is inspired by but not identical to  the code from samba-operator.
This PR is proposed to allow for easier update of our yamls, e. g. workflow yamls in future PRs.
> Add yamllint checking

- Makefile
Assert that if the CONTAINER_CMD is docker that the --arch flag will not be passed to the container engine. Only pass an --arch flag (to podman) if BUILD_ARCH is set to some non-empty value.
> makefile: prevent passing an unknown --arch argument to docker

- images/ad-server/Containerfile.fedora
- images/common/install-sambacc-common.sh
- images/server/Containerfile.centos
- images/server/Containerfile.fedora
In the previous release we made sure to "pin" a version of both sambacc and samba. The former was done by an "embedded" build which is something we've moved away from. So this adds back the ability to require a sambacc version in a way more similar to how we previously required a samba version.
> images: support a SAMBACC_VERSION_SUFFIX to force a sambacc version

- images/ad-server/Containerfile.fedora
- images/client/Containerfile.fedora
- images/server/Containerfile.fedora
Update the base images that use fedora to fedora 38. Fedora 38 has already been out some months already. Now is the perfect time to update them.
> images: update fedora base images to fedora 38

- examples/kubernetes/pv.yml
- examples/kubernetes/pvc.yml
- examples/kubernetes/samba-ad-server-deployment.yml
- examples/kubernetes/samba-ctdb-dm-sset.yml
- examples/kubernetes/samba-ctdb-sset.yml
- examples/kubernetes/sambadeployment.converged.yml
- examples/kubernetes/sambadeployment.yml
- examples/kubernetes/sambadmpod.yml
- examples/kubernetes/sambapod.yml
- tests/files/samba-ad-server-deployment.yml
- tests/files/samba-domain-member-pod.yml
The title says it all. Tedious but straightforward.  Gets rid of the noise when running `make check-yaml` so you can more easily see if you've introduced an error or warning.
I disagree with yaml lint on certain trailing comments, but I just went with the flow for now.
> reformat yaml files to remove yamllint warnings

- .gitlint
Configure gitlint to ignore lines that start like `[1]: ` or `[2] ` such that we can have  long text like URLs in the commits without triggering other gitlint body     rules.
PR contains two test commits to demonstrate the change that must be removed prior to merging.
> gitlint: allow commit messages to contain long footnotes

- hack/build-image
Fixes: #151 
Late in the development of `build-image` I made additional_tags a list of tuples rather than a list of strings in order to make filtering simpler but `push` function was never updated to match. This quick fix gets `--push` mode working again.
> hack: fix --push option to build-image

- docs/release-process.md
Finally, I've gotten around to documenting the release process based on my notes from the release in June. This is loosely based on the release process doc I wrote for sambacc and svcwatch.
> docs: add release process document

- docs/development.md
- images/common/install-sambacc-common.sh
While hacking on a some sambacc stuff I realized I had not written down the technique I used to build samba-container images that use work-in-progress sambacc code and had to partially re-invent it. Fix one issue I found while doing that and start a developers guide document by documenting this  process that I used to test out development branches of sambacc in a proper samba-container image.
> docs: start a developer's doc with a tip related to building sambacc dev branches

- images/ad-server/Containerfile.fedora
- images/client/Containerfile.fedora
- images/server/Containerfile.fedora
With the recent release of samba-container and the somewhat recent release of Fedora 39, now is a good time to update the fedora version we are tracking.
> images: update fedora base images to fedora 39

- hack/build-image
Avoid passing the --arch option to podman for building the host architecture.
Add an option to skip adding tags meant primarily for backwards compatibility with the earlier makefile based builds.
> hack: some tweaks for the build-image script

- .github/workflows/container-image.yml
- hack/build-image
- images/ad-server/install-packages.sh
- images/server/Containerfile.centos
- images/server/Containerfile.fedora
- images/server/install-packages.sh
Ensure ceph support exists in the centos based images. Ceph support (for the samba vfs module and sambacc) was already present in the Fedora based images due to (a) fedora packages cephs in the main repos (b) the samba and sambacc RPMs having correct dependencies, as long as the proper samba  vfs modules are selected. These changes will enable ceph libraries to be installed on the samba server image when based on centos and works around some issues in the sambacc dependencies as well.
Add a new package source called "devbuilds" that is valid for centos based images. It enables both the samba nightly builds repo (like the existing "nightly" package source) as well as dev builds from ceph's main branch.
In order to do this cleanly the script and images are refactored slightly to re-organize …
> Add ceph support for centos based images

- .github/workflows/container-image.yml
- hack/build-image
The following changes update the build-image script so that it's easier to update the tags for existing images and helps control what tags are pushed when the push command is invoked.
Then we restructure the push job so that it avoids rebuilding the images we just built and test and instead reimports them from the artifacts and then uses the new retag command to fix up the tags and distro base followed by pushing them as both unqualified (`latest`, `nightly`) tags and fully-qualified tags.
Finally, we enable pushing the `samba-server:nightly-centos-amd64` and `samba-server:devbuilds-centos-amd64` to quay.io. The latter will be used for testing the ongoing SMB on Ceph work occurring in the Ceph project.
> workflows: restructure the push job

- images/ad-server/Containerfile.centos
- images/ad-server/Containerfile.fedora
- images/ad-server/Containerfile.opensuse
_/usr/sbin/samba_ also comes with a similar option as others to print logs to standard output. Make use of `SAMBA_SPECIFICS` argument to specify required value to finally run with `--debug-stdout` option.
depends on https://github.com/samba-in-kubernetes/sambacc/pull/106
> images/ad-server: Send debug output to standard output

- .github/workflows/container-image.yml
Add a workflow_dispatch event trigger so that the team (specifically, me when I am being impatient) can trigger a manual CI run and eventually image push to quay.io
> workflows: allow manually running the ci job

- .github/workflows/container-image.yml
Eliminate github's warning ("Node.js 16 actions are deprecated") by upgrading to 'checkout@v4'.
fixes #169
> workflows: upgrade to checkout@v4

- images/ad-server/Containerfile.fedora
- images/client/Containerfile.fedora
- images/server/Containerfile.fedora
With the recent release of samba-container and the recent-ish release of Fedora 40, now is a good time to update the fedora version we are tracking.
> images: update fedora base images to fedora 40

- images/server/install-packages.sh
`ctdb-rados-mutex` subcommand to `samba-container` expects the required rados helper binary to be present for execution. Therefore install the necessary ctdb-ceph-mutex package providing ctdb_mutex_ceph_rados_helper in various image flavours.
> images/server: Install ctdb-ceph-mutex for rados helper

- .github/workflows/container-image.yml
A while back we enabled running workflow manually in the action (with a button on the github ui) via the workflow_dispatch type. However, this action doesn't run the 'push' step because push is only included with a scheduled run or a merged pr. Rework the line so that push is performed for scheduled runs, merged prs, or manual runs. This is useful in case something samba-container depends on is updated and one doesn't feel like waiting all day for a scheduled run.
> workflows: allow push on manually run workflows

- hack/build-image
```
Traceback (most recent call last):
File "/root/master/./hack/build-image", line 726, in <module>
main()
File "/root/master/./hack/build-image", line 716, in main
_action(cli, img)
File "/root/master/./hack/build-image", line 513, in retag
container_tag(cli, cid, *tags)
File "/root/master/./hack/build-image", line 268, in container_tag
args += [tag] + list(tags)
UnboundLocalError: local variable 'args' referenced before assignment
```
> hack: Fix variable reference before assignment

- docs/release-process.md
Add a copy-and-paste-able shell script that one can run to generate the downloads section of the release notes. This saves the effort of copy and pasting digests out of the quay.io ui.
> docs: add a script to do the tedious work of fetching digests

- .github/workflows/container-image.yml
- hack/build-image
Extends the GA workflow to build and push Fedora and OpenSUSE arm64 container images. The `build-image` script has been modified to use Docker Buildx for cross-building.
Preparation for: https://github.com/samba-in-kubernetes/samba-container/pull/179
Fixes: https://github.com/samba-in-kubernetes/samba-container/issues/155
> build Fedora+OpenSUSE arm64 container images

- README.md
improve some links and mention that the containers are used by ceph.
> readme: some updates to the README

- images/server/install-packages.sh
Resilient Storage is only required when ctdb packages are installed from standard repositories. Therefore avoid enabling it for container builds with samba nightly rpms.
> images/server: Enable resilientstorage only for non-nightly builds

- docs/release-process.md
- hack/release-gen-download-section.sh
This extracts the  script added to the the release process document as in PR #185 from the document.
This script can be invoked to create the downloads section for the release notes for a given release.
> hack: extract release script to generate download info from  the release doc

- images/server/install-packages.sh
Dynamically determine the host architecture instead of hardcoded value 'x86_64'.
> images/server: Do not hardcode architecture for devbuilds

- images/server/install-packages.sh
Remove the hardcoded 'x86_64' value from generated repo file for ceph development builds and use standard `$basearch` dnf repo variable.
> images/server: Use `$basearch` in ceph devbuilds repo file

- images/common/install-sambacc-common.sh
this explicitly implements a preference order for sambacc
custom installation sources like so:
local repo ->  -> rpm ->  wheel   -> copr.
It makes the output a bit more verbose while at it.
overall, the behavior of the sambacc installation is made a bit more consistent and predictable
> common:  implement an explicit preference order in sambacc installation

- images/server/install-packages.sh
The libcephfs-proxy2 package is required to enable proxy support for the vfs_ceph_new samba vfs module.
Fixes: #196
> images/server: add libcephfs-proxy2 to server image

- hack/build-image
Conditionally set the samba specifics value for ctdb_rados_mutex_skip_reg based on source. When the source is a samba master build (nightly, devbuilds) we want to set this specifics flag.
Reformat source of `hack/build-image` with black as I noticed it had many small issues when reading it over today.
> hack: conditionally set samba specifics value based on source

- .github/workflows/container-image.yml
Github has disabled ubuntu 20.04:
`This is a scheduled Ubuntu 20.04 retirement.`
Update to ubuntu latest to find out what jq issue the comment was referring to.
> workflows: use ubuntu-latest everywhere

- images/server/install-packages.sh
- Add a default case to define $package_selection.
- Enable EPEL irrespective of $install_packages_from.
- Update ceph version to squid for default centos.
> images/server: Few improvements to install-packages.sh

- images/server/install-packages.sh
For the case of default package source on CentOS, we switch the repository from standard to Storage SIG for early consumption of latest Samba versions. Use the common release package name instead of specific version for both Ceph and Samba packages while enabling Storage SIG repositories.
> images/server: Install Storage SIG release packages for samba and ceph

- .github/mergify.yml
Mergify rules doesn't check the status of pull requests before adding the "priority-review" label. In addition to the existing rules it only makes sense to add the label if the pull request is in open state.
> mergify: Restrict the addition of "priority-review" label

- .gitignore
- examples/custom-server.ini
- hack/build-image
- images/server/Containerfile.centos
- images/server/install-packages.sh
Depends on: #210 
Depends on: #212
This PR fleshes out something I've been wanting for a while, a way to record and repeatedly build custom samba server images. These customizations include things like bringing in samba, ceph, or other dependencies from special rpm repos; tweaking other build container build arguments; or using custom arguments not on the command line, so that I don't have to rely heavily on my shell history.
Another special customization is the ability to build and install sambacc from a git checkout. This allows for a faster and cleaner build and install of a sambacc development branch. It is based on the instructions https://github.com/samba-in-kubernetes/samba-container/blob/master/docs/development.md#build-stage
The pr starts off with various cleanup patches an prep …
> hack: support even more customization

- images/server/install-packages.sh
The parameters for the base shaman url that was used to determine the chacra repository link did not have `status=ready` resulting in invalid chacra urls as part of the json response. Make sure that we fetch with `status=ready` so as to create repo files with valid base url.
> images/server: Fix ceph shaman base url parameters

- images/server/install-packages.sh
- Use Samba v4.23 for `ceph20`.
- Switch to Storage SIG ceph tentacle packages for `ceph20` on CentOS.
- Generalize a switch case for CentOS based package selection.
> images/server: Updates to package installation
